version: '3'

services:

  mpp-solar:
      
    build:
      context: .
      dockerfile: Dockerfile

    container_name: mpp-solar
    stdin_open: true  
    tty: true      
    privileged: false
    restart: always

    devices:
      - /dev/ttyMOD2:/dev/ttyMOD2
      - /dev/ttyMOD3:/dev/ttyMOD3
