version: '3'

services:

  sila5kw:
      
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: sila5kw
    stdin_open: true  
    tty: true  
    environment:
      - INVERTER_DEVICE=\/dev\/ttyMOD2
      - INVERTER_QPIRI=104
      - MQTT_SERVER=192.168.1.20
      - MQTT_PORT=1883
      - MQTT_TOPIC=homeassistant
      - MQTT_DEVICENAME=sila5kw
      - MQTT_MANUFACTURER=Sila
      - MQTT_MODEL=Sila5000MO
      - MQTT_SERIAL=92932109105176
      - MQTT_VER=00072.00
      - MQTT_USERNAME=mqtt
      - MQTT_PASSWORD=123592
    
    privileged: false
    restart: always

    #volumes:
        #- ./config/:/etc/inverter/

    devices:
      - /dev/ttyMOD2:/dev/ttyMOD2
      #- /dev/ttyMOD3:/dev/ttyMOD3

  sila8kw:
      
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: sila8kw
    stdin_open: true  
    tty: true  
    environment:
      - INVERTER_DEVICE=\/dev\/ttyMOD3
      - INVERTER_QPIRI=109
      - MQTT_SERVER=192.168.1.20
      - MQTT_PORT=1883
      - MQTT_TOPIC=homeassistant
      - MQTT_DEVICENAME=sila8kw
      - MQTT_MANUFACTURER=Sila
      - MQTT_MODEL=Sila8000
      - MQTT_SERIAL=96342108100227
      - MQTT_VER=00054.01
      - MQTT_USERNAME=mqtt
      - MQTT_PASSWORD=123592
      
    privileged: false
    restart: always

    #volumes:
        #- ./config/:/etc/inverter/

    devices:
      #- /dev/ttyMOD2:/dev/ttyMOD2
      - /dev/ttyMOD3:/dev/ttyMOD3
